### ISSUE TITLE
How to run this project in Eclipse IDE?

### ISSUE THREAD

**Issue by coding-geek21** [e-francis/Guru99-Selenium-Test-with-TestNG-framework#1]
Hi recently i found your project and it looks quite interesting!
can you help me in running this project in Eclipse IDE?
I just downloaded and imported to eclipse IDE..

**Comment by coding-geek21** [comment]
I got result like this when i tried to run the testng.xml file. How to fix the "No SLF4J providers were found" error? and why are the tests skipped ?


![image](https://user-images.githubusercontent.com/53329034/236518164-04dfc9f0-1057-45bc-a9da-f6fbf66a6a18.png)
![image](https://user-images.githubusercontent.com/53329034/236517336-a04d45f4-1736-44f7-8bba-5ed2c5580727.png)

**Comment by e-francis** [comment]
Hello, I am so sorry for responding late, as I recently saw your message. If you haven't fixed this issue, did you try running `mvn clean install` in the terminal at the root of the project directory, before running the tests? Please let me know how I can help you further. Thank you.

**Comment by coding-geek21** [comment]
Thank you!
I already fixed that issue.
